way: 0 # 0 根据run_id 挑选设备 单发  1 根据 run_id 挑选设备分布式（先只支持两台）  2  run_id 并发
common: # 公用
  run_id: 0 # 执行的设备 根据devices下标来挑选。  数字 或者 列表 [0,2]
  rpc_url: http://127.0.0.1:8082/rpc
  account_open: !!str false
  phone_number: 88887541083
  verify_code: 123456
  trade_code: !!str 000000
  member_id: !!str 10395894
  target_aaid: !!str 50086155
  nz_aaid: !!str 50086154
  appPackage: tv.danmaku.bili
  appActivity: .MainActivityV2
devices:
  - desc: 设备名称_小米,appium启动服务端口号_4723
    port: !!int 4723
    env: 安卓  # android / ios 安卓/ios
    desired_caps:
      platformName: Android
      deviceName: HUAWEI
      appPackage: tv.danmaku.bili
      appActivity: .MainActivityV2
      unicodeKeyboard:  #支持中文输入
      resetKeyboard: true  # 重置输入法
      noReset: true
      platformVersion: !!str 10
#      udid: 10.10.1.37:3455
      udid: ff41f8c4
      newCommandTimeout: 120
      automationName: UiAutomator2
      settings[waitForIdleTimeout]: 100 # 加快动态页面的定位
      language: "zh" # 如果要切换英语  设置为en
      locale: "cn" # 切换为 en
  - desc: 设备名称_HUAWEI,appium启动服务端口号_4725
    port: !!int 4725
    env: 安卓  # android / ios 安卓/ios
    desired_caps:
      platformName: Android
      deviceName: HUAWEI
      appPackage: global.longbridge.android.debug
      appActivity: global.longbridge.android.LaunchActivity
      unicodeKeyboard: true
      resetKeyboard: true
      noReset: true
      platformVersion: !!str 10
      udid: 10.10.0.193:3499
      newCommandTimeout: 120
      automationName: UiAutomator2